/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cricketclub;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Saajid Muhammad
 */
public class EditInfo extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form EditInfo
     */
    public EditInfo() {
        initComponents();
        this.setLocationRelativeTo(null);
        con = DBconnect.connect();
        ClubName();
    }

    
     public void ClubName()
    {
        try{
            String q = "SELECT * FROM club_info ";
            
            pst = con.prepareStatement(q);
            rs = pst.executeQuery();
            
            while(rs.next())
            {
                String cname = rs.getString("Club_Name");
                String owner = rs.getString("Club_Owner");
                String regid = rs.getString("Reg_Id");
                
                
                jTextField_club.setText(cname);
                jTextField_owner.setText(owner);
                jTextField_regid.setText(regid);
                
            
            
            }
            
        
        
        
        }
        
        catch(Exception e)
        {
            System.out.println(e);
        }
    
    
    
    
    
    
    
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_owner = new javax.swing.JTextField();
        jTextField_club = new javax.swing.JTextField();
        jTextField_cid1 = new javax.swing.JTextField();
        jTextField_regid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Club Info - Cricekt Club Managment System");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(850, 500));
        setMinimumSize(new java.awt.Dimension(850, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "Change Club Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Agency FB", 1, 30), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Change");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(320, 230, 100, 31);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Club Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(35, 82, 81, 29);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(200, 230, 100, 31);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(17, 84, 0, 0);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 84, 0, 0);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Owner Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(35, 122, 101, 29);

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registerd Id");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(35, 162, 92, 29);

        jTextField_owner.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jPanel1.add(jTextField_owner);
        jTextField_owner.setBounds(210, 120, 200, 29);

        jTextField_club.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jTextField_club.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_clubActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_club);
        jTextField_club.setBounds(210, 80, 200, 29);

        jTextField_cid1.setFont(new java.awt.Font("Agency FB", 0, 1)); // NOI18N
        jTextField_cid1.setText("1");
        jTextField_cid1.setEnabled(false);
        jPanel1.add(jTextField_cid1);
        jTextField_cid1.setBounds(2, 302, 6, 8);

        jTextField_regid.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jPanel1.add(jTextField_regid);
        jTextField_regid.setBounds(210, 160, 200, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cricketclub/BGP-1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(340, 40, 40, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(160, 90, 491, 313);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Main Menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 11, 100, 40);

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cricketclub/012_power-512.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(10, 420, 40, 35);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cricketclub/BGP-3.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 920, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x =  JOptionPane.showConfirmDialog(null, "Do You Really Want to Change Club Name");

        if (x==0)
        {

            String cid = jTextField_cid1.getText();
            String cname = jTextField_club.getText();
            String owner = jTextField_owner.getText();
            String regid = jTextField_regid.getText();
            
         

            if(cname.equals(""))
            {
                JOptionPane.showMessageDialog(null,"Please Enter Your Club Name");
            }
        
            
            else
            {

                String sql = "UPDATE club_info SET Club_ID = '"+ cid +"',Club_Name = '"+ cname +"',Club_Owner = '"+ owner +"',Reg_Id = '"+ regid +"' WHERE Club_ID = '"+ cid +"'";

                try
                {
                    pst = con.prepareStatement(sql);
                    pst.execute();

                    JOptionPane.showMessageDialog(null,"Your Club Info was Changed");

                }
                catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null, e.toString(), "InfoBox", JOptionPane.INFORMATION_MESSAGE);

                }

            }
        }
        
        ClubName();

       

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
        new ClubInfo(). setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField_clubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_clubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_clubActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        setVisible(false);
        Homepage hp = new Homepage();
        hp.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int x =  JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Exit?");

        if (x==0)
        {

            System.exit(0);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_cid1;
    private javax.swing.JTextField jTextField_club;
    private javax.swing.JTextField jTextField_owner;
    private javax.swing.JTextField jTextField_regid;
    // End of variables declaration//GEN-END:variables
}
